### ISSUE TITLE
Misconfigured Radio, ID 0 causing Analog_Bridge to exit, not respawn

### ISSUE THREAD

**Issue by jturning** [DVSwitch/Analog_Bridge#12]
While playing with TGIF, when someone with a misconfigured radio comes on with ID 0 it crashes Analog_Bridge. I believe I've seen ID 0 with other cross mode projects, so this would be a normal thing to pop up from time to time. 

MMDVM_Bridge log:
M: 2020-05-25 21:47:08.927 DMR Slot 2, received network voice header from 0 to TG 31665
M: 2020-05-25 21:47:10.430 DMR Slot 2, network watchdog has expired, 0.1 seconds, 0% packet loss, BER: 0.0%

Analog_Bridge.log:
F: 2020-05-25 21:47:08.927 Repeater ID (0) can not be the same as subscriber ID (0). Fatal error exiting

**Comment by K2IE** [comment]
I have observed this as well:

F: 2020-08-14 11:00:15.609 Repeater ID (0) can not be the same as subscriber ID (0). Fatal error exiting

**Comment by K2IE** [comment]
Analog Bridge failed again several times today on the same "0" id issue.  As a workaround, I commented out the systemd unit line that prevents restart on exit code of 254 and at least it restarts.  But this ought to be prioritized for a fix.

**Comment by N4IRS** [comment]
Fixed
