### ISSUE TITLE
DVSwitch configurations assumed shared

### ISSUE THREAD

**Issue by hsoj** [DVSwitch/Analog_Bridge#13]
The Analog_Bridge binary appears to assume it's being ran on the same host reading the same DVSwitch.ini file as the MMDVM_Bridge binary which causes confusion when both are running individually (say in their own containers).

The Analog_Bridge binary looks at the TX port configuration in it's DVSwitch.ini file for it's RX port, and this is not really documented anywhere.

Is the source code available so that these small nuances can be addressed within a fork?

**Comment by N4IRS** [comment]
Joshua,
Thanks for your comments. No, the source is not available. How would you suggest this be "addressed" ?

Steve N4IRS

**Comment by MrBungle42** [comment]
AB does not do this. DVSwitch.sh does. This script is open and you can
modify it as you please.
