### ISSUE TITLE
Problem with gatewayDmrID 

### ISSUE THREAD

**Issue by sp2ong** [DVSwitch/Analog_Bridge#5]
Hi Steve,

Is it possible to correct the problem with use DMRiD + SSID in gatewayDmrId ?
We have run Allstralink with EchoLink/USRP to DMR link and we need use DMRID+SSID in "gatewayDmrId"
When we put DMRId repeater (260454)+ SSID (99) for example
26045499 Analog_Bridge send ID which is used to transmitting
for example 9268283

It will be nice to possible use in gatewayDmrId 
DmrID repeater + SSID
and
DmrId private +SSID
The problem is in Analog_Bridge v1.4.1 and MMDVM_Bridge in log show

Begin TX: src=**9268283** rpt=26045440 dst=40 slot=2 cc=1 metadata=**26045499**

**Comment by N4IRS** [comment]
gatewayDmrId is used as the user DMRID that is transmitting. Why would a user have a SSID appended to it? As far as I know 9 characteruser DMRIDs are not valid for users.

**Comment by sp2ong** [comment]
Hi Steve
Ok, you are right. We have meet with problem when we setup ALS  <-> DMR gateway. When the gateway was setup for repeater callsign which have 6 digi in DMRID and when we put DMR ID repeater in "gatewayDmrId" field we have to meet some problems with a link connected to BM TG. So, I thought that when we put in gatewayDmrID DmrID+SSID for repeater it will be allowed to send traffic but Analog_Bridge generates where strange Id to MMDVM_Bridge.

**Comment by sp2ong** [comment]
Steve

OK, if we can not use DMRid+SSID in "gatewayDmrID" in Annalog_Bridge.ini it will be good to prevent this to not send any traffic to MMDVM_Bridge if gatewayDmrID has id not equal 7 number digi.
At current, if anybody put in gatewayDmrID the id 8 or 9 numbers digi Analog_Bridge send traffic with very strange DMR Id for example if we put in gatewayDmrID  26045499  the src filed in MMDVM_Bridge is 9268283

BTW
I have question to allstarlink. Is it possible to connect from console asterik to EchoLink node?

I try: rpt fn 1999 *3xxxxxx  where xxxxxx is number echolink node , not works


73 Waldek

**Comment by N4IRS** [comment]
Assuming echolink is connected to node 1999
rpt **fun** 1999 *3xxxxxx where xxxxxx is number echolink node

**Comment by sp2ong** [comment]
I have a private node 1999 and running echolink node with number 819905. But I would like connect my echolink node 819905 with another echolink node. Is it possible ?

**Comment by N4IRS** [comment]
Yes, Move this to groups.io in the DVSwitch/AllStarLink subgroup.
